name: shikayat
description: Shikayat is an college Complaint Management Application (CMA) developed in flutter and firebase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  modal_progress_hud_nsn: ^0.4.0
  widget_and_text_animator: ^1.1.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/